### ISSUE TITLE
`set-version.sh` misses some files

### ISSUE THREAD

**Issue by lawrence-forooghian** [ably/ably-cocoa#1477] opened 2022-08-18 14:56 UTC
See https://github.com/ably/ably-cocoa/commit/a554ae14a5c1632d7540f306fc3948e31f22a95d.

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-2577) by [Unito](https://www.unito.io)

**Comment by maratal** [comment] 2022-08-19 14:29
Duplicate of https://github.com/ably/ably-cocoa/issues/1447

**Closed** 2022-08-19 14:29 UTC
