### ISSUE TITLE
Push deactivate event is fired before whole deactivating process is finished

### ISSUE THREAD

**Issue by lukasz-szyszkowski** [ably/ably-cocoa#1146] opened 2021-06-30 11:44 UTC
### Which version of the Ably SDK are you using? 
`1.2.4`

### On which platform does the issue happen? 
`iOS`

### What did you do?
I added `didDeactivateAblyPush` delegate method

```swift
class AblyHelper: NSObject {
    static let shared = AblyHelper()
    
    private let key = "xxx:xxxx"
    private(set) var realtime: ARTRealtime!
    private(set) var rest: ARTRest!
    
    private override init() {
        super.init()
        
        let options = ARTClientOptions(key: key)
        options.logLevel = .verbose
        options.clientId = UIDevice.current.name
        options.pushRegistererDelegate = self
        
        self.realtime = ARTRealtime(options: options)
        self.realtime.push.activate()
        self.rest = ARTRest(options: options)
    }
    
}

extension AblyHelper: ARTPushRegistererDelegate {
    func didActivateAblyPush(_ error: ARTErrorInfo?) {}
    
    func didDeactivateAblyPush(_ error: ARTErrorInfo?) {
        exit(0)
    }
}
```
I called `deactivate()` on ARTPush object somewhere in code ...
```swift
AblyHelper.shared.realtime.push.deactivate()
```

### What did you expect to happen?
SDK should deactivate the device on the server and clear cached credentials on the device. After that, 
```swift
func didDeactivateAblyPush(_ error: ARTErrorInfo?) {
    exit(0)
}
```
should be fired.

### What happened instead?
```swift
func didDeactivateAblyPush(_ error: ARTErrorInfo?) {
    exit(0)
}
```
is fired before all deactivating tasks are done

### How to check it?
```swift
func showIdentityToken() {
    guard
        let tokenData = UserDefaults.standard.value(forKey: "ARTDeviceIdentityToken") as? Data,
        let tokenInfo = ARTDeviceIdentityTokenDetails.unarchive(tokenData)
    else {
        print("INDENTITY TOKEN: doesn't exist")
        return
    }

    print("INDENTITY TOKEN:\n\(tokenInfo.token)")
}
```
there should be `IDENTITY TOKEN: doesn't exist` in the console. However, instead of this, there is still the previous `identityToken`.

### Workaround
```swift
func didDeactivateAblyPush(_ error: ARTErrorInfo?) {
    DispatchQueue.main.asyncAfter(deadline: .now() + 1.5) {
        exit(0)
    }
}
```
add a delay before terminating the app.

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-1009) by [Unito](https://www.unito.io)

**Comment by maratal** [comment] 2021-11-27 18:28
I've created demo project based on the code in this issue. Couldn't reproduce this behavior
[PushDeactivateDemo.zip](https://github.com/ably/ably-cocoa/files/7612240/PushDeactivateDemo.zip)
.

**Comment by lukasz-szyszkowski** [comment] 2021-12-01 11:04
> I've created demo project based on the code in this issue. Couldn't reproduce this behavior: [PushDeactivateDemo.zip](https://github.com/ably/ably-cocoa/files/7612240/PushDeactivateDemo.zip)
> 
> ~Found another issue in the process though - #1236~

Yea, because you missed `exit(0)` it should look like this:
```swift
extension AblyHelper: ARTPushRegistererDelegate {
    
    func didActivateAblyPush(_ error: ARTErrorInfo?) {
        Self.printIdentityToken()
    }
    
    func didDeactivateAblyPush(_ error: ARTErrorInfo?) {
        Self.printIdentityToken()
        exit(0)
    }
}
```
I expect that after the call `didDeactivateAblyPush` the token is cleared, no matter if the app crashes or not. That's the case.
I assume that `didDeactivateAblyPush` is called too early.

**Comment by maratal** [comment] 2021-12-01 14:57
I believe you try it against wrong version of ably-cocoa. Try this commit https://github.com/ably/ably-cocoa/pull/1184/commits/09256037a2ac52bef7d3cf14e701fea0ee314cd1

**Comment by lukasz-szyszkowski** [comment] 2021-12-01 15:14
> I believe you try it against wrong version of ably-cocoa. Try this commit [0925603](https://github.com/ably/ably-cocoa/commit/09256037a2ac52bef7d3cf14e701fea0ee314cd1)

yea, I tried it against official release (1.2.7). I will try against this https://github.com/ably/ably-cocoa/commit/09256037a2ac52bef7d3cf14e701fea0ee314cd1 and I'll let you know here.

**Comment by lukasz-szyszkowski** [comment] 2021-12-01 15:30
Nothing changed, the token still exists after "crash" (`exit(0)`) on `deactivate()`

https://user-images.githubusercontent.com/47628502/144263351-ef4784d2-1321-4d86-b263-7192b87ae7ee.mp4

Podfile.lock
```
PODS:
  - Ably (1.2.7):
    - AblyDeltaCodec (= 1.3.2)
    - msgpack (= 0.4.0)
  - AblyDeltaCodec (1.3.2)
  - msgpack (0.4.0)

DEPENDENCIES:
  - Ably (from `https://github.com/ably/ably-cocoa.git`, commit `09256037a2ac52bef7d3cf14e701fea0ee314cd1`)

SPEC REPOS:
  trunk:
    - AblyDeltaCodec
    - msgpack

EXTERNAL SOURCES:
  Ably:
    :commit: 09256037a2ac52bef7d3cf14e701fea0ee314cd1
    :git: https://github.com/ably/ably-cocoa.git

CHECKOUT OPTIONS:
  Ably:
    :commit: 09256037a2ac52bef7d3cf14e701fea0ee314cd1
    :git: https://github.com/ably/ably-cocoa.git

SPEC CHECKSUMS:
  Ably: f627c0c2e4489785b74d33d2c1287edeb9c6a7be
  AblyDeltaCodec: 783d017270de70bbbc0a84e4235297b225d33636
  msgpack: c85f6251873059738472ae136951cec5f30f3251

PODFILE CHECKSUM: 48447d06fa2a4a7ec70e5108b12b0618c583beba

COCOAPODS: 1.11.2
```

**Comment by maratal** [comment] 2021-12-01 17:26
I see on 0:20 that "Token doesn't exist." and crash after that.

**Comment by lukasz-szyszkowski** [comment] 2021-12-01 17:44
> I see on 0:20 that "Token doesn't exist." and crash after that.

Later (after 00:20) I start the app again, and I tapped "Print Token" and you can see that token still exists, but it shouldn't.

**Comment by maratal** [comment] 2021-12-01 18:12
It can be an issue that storage has no chance to persist changes because of this crash. Still can't reproduce on my device though, it saves it before exit.. Upon next run token doesn't exist 😅

**Comment by lukasz-szyszkowski** [comment] 2021-12-02 07:09
Ok, let's leave it open then. Maybe someday we'll back to this again.

**Comment by jamienewcomb** [comment] 2021-12-20 08:38
@maratal lets close this issue if we are not planning to do this

**Comment by maratal** [comment] 2021-12-21 23:01
Closing issue due to lack of evidence.

**Closed by maratal** 2021-12-21 23:01 UTC
