### ISSUE TITLE
Unnecessary presence update events after restoring a connection

### ISSUE THREAD

**Issue by DCleymans** [ably/ably-cocoa#1781] opened 2023-06-29 07:17 UTC
{panel:bgColor=#deebff}

#### HubSpot linked tickets:
* [SELF - Tunify - Exceeding limits (Ticket ID: 1714326849)](https://app.hubspot.com/contacts/6939709/ticket/1714326849)

~_(please, do not edit or duplicate in description)_~
{panel}

### Which version of the Ably SDK are you using? 
1.2.20

### On which platform does the issue happen? 
iOS16.5.1

### Are you using Carthage? 
no

### Are you using Cocoapods? 
no

### Which version of Xcode are you using? 
14.3.1

### What did you do?
The iOS app is present in a channel:

![width=200,height=183](https://github.com/ably/ably-cocoa/assets/12541466/53ecb561-8da1-47d1-a1a1-a66b8d894c4b)

When the app goes to the background, the ARTRealtime connection goes to a disconnected state after a few seconds.
The app leaves the presence, as expected:

![width=200,height=183](https://github.com/ably/ably-cocoa/assets/12541466/37b56022-365e-470a-9296-ffa1475b22c4)

When the app is going back to the foreground,  the ARTRealtime connection is restored (connected state) and the app enters the presence once again. The app might also push an extra 'update' event on the presence of the channel.

![width=200,height=183](https://github.com/ably/ably-cocoa/assets/12541466/bc802c9b-72c0-4c07-a0cb-cd35436d8d84)

The extra 'update' event is not expected. When the app moves multiple times to the background, lost its connections and restoring the connection when bringing back to the foreground, the extra 'update' events keep stacking. After a while, multiple 'update' events can be seen on one connection restore:

![width=200,height=183](https://github.com/ably/ably-cocoa/assets/12541466/f0567083-0744-4878-a07e-e27de5ba94e2)

Our app does not send any update events from our code.

We have users that keep the app open for multiple days, the app goes many times to the background / foreground. This results in more than 50 update messages each time the app restores its connection.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-4552) by [Unito](https://www.unito.io)

**Comment by lawrence-forooghian** [comment] 2023-06-29 12:13
Thank you for the report @DCleymans, this does not sound like an expected behaviour. We'll look into it.

**Comment by maratal** [comment] 2024-03-08 16:42
Please check [v1.2.26](https://github.com/ably/ably-cocoa/releases/tag/1.2.26)
Should be fixed now.

**Comment by lawrence-forooghian** [comment] 2024-04-23 12:25
Closing this one since we haven’t heard back from the reporter. Feel free to re-open if this is still affecting you, @DCleymans.

**Closed by lawrence-forooghian** 2024-04-23 12:25 UTC
Labels: bug
